"""Recreate schema

Revision ID: 65472d1696a5
Revises: 
Create Date: 2025-02-06 12:27:52.586971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65472d1696a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=126), nullable=False),
    sa.Column('activity', sa.JSON(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('share_code', sa.String(length=126), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_code')
    )
    op.create_table('user_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
